server:
  port: 8090
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/crystaljingli/spring-cloud
          #uri: https://github.com/crystaljingli/{application}
          username: lijinghaitang
          password: ******