server:
  port: 8000
spring:
  application:
    name: provider-user
eureka:
  client:
     service-url:
          #default-zone: http://localhost:8761/eureka,http://localhost:8761/eureka 注册多个 , 分割
          default-zone: http://localhost:8761/eureka
     instances:
          preprefer-ip-address: true

